"""relating apps and subs

Revision ID: 1de735bf3e7b
Revises: 6bb584c594ae
Create Date: 2025-09-23 10:56:33.333447

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1de735bf3e7b"
down_revision: Union[str, Sequence[str], None] = "6bb584c594ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications", sa.Column("ticket_id", sa.String(length=40), nullable=True)
    )
    op.add_column(
        "applications", sa.Column("owner_id", sa.String(length=40), nullable=True)
    )
    op.create_foreign_key(None, "applications", "users", ["owner_id"], ["id"])
    op.create_foreign_key(None, "applications", "submissions", ["ticket_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "applications", type_="foreignkey")
    op.drop_constraint(None, "applications", type_="foreignkey")
    # ### end Alembic commands ###

    op.drop_column("applications", "ticket_id")
    op.drop_column("applications", "owner_id")
