"""added is_completed column and fixed index unique issue

Revision ID: 31510adf42c8
Revises: db0e93e8bf5a
Create Date: 2025-09-03 17:05:09.014093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31510adf42c8'
down_revision: Union[str, Sequence[str], None] = 'db0e93e8bf5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_completed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'is_completed')
    # ### end Alembic commands ###
