"""added relationship b/w checklist and responses

Revision ID: 469c588fc136
Revises: a152e24a6f59
Create Date: 2025-09-16 19:26:15.389959

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "469c588fc136"
down_revision: Union[str, Sequence[str], None] = "a152e24a6f59"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_responses", type_="foreignkey")
    op.drop_index("ix_user_responses_checklist_id", table_name="user_responses")
    op.drop_column("user_responses", "checklist_id")

    # ### end Alembic commands ###
