"""added rlationship b/w admin and sub ass

Revision ID: 6a40ac2d3464
Revises: e1a2cbf9cbe4
Create Date: 2025-09-18 23:09:21.485991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a40ac2d3464'
down_revision: Union[str, Sequence[str], None] = 'e1a2cbf9cbe4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('assessed_by', sa.String(length=40), nullable=True))
    op.create_foreign_key(None, 'submissions', 'users', ['assessed_by'], ['id'])
    op.create_foreign_key(None, 'user_responses', 'checklists', ['checklist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_responses', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'assessed_by')
    # ### end Alembic commands ###
