"""app auto create

Revision ID: 6bb584c594ae
Revises: 6a40ac2d3464
Create Date: 2025-09-22 10:25:28.257163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6bb584c594ae'
down_revision: Union[str, Sequence[str], None] = '6a40ac2d3464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'platform',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('applications', 'region',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.alter_column('applications', 'owner_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    op.alter_column('applications', 'provider_name',
               existing_type=mysql.VARCHAR(length=666),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'provider_name',
               existing_type=mysql.VARCHAR(length=666),
               nullable=False)
    op.alter_column('applications', 'owner_name',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    op.alter_column('applications', 'region',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.alter_column('applications', 'platform',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###
