"""added relationship b/w checklist and responses for real

Revision ID: 7ba26179c1fd
Revises: 469c588fc136
Create Date: 2025-09-16 19:33:13.293512

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ba26179c1fd"
down_revision: Union[str, Sequence[str], None] = "469c588fc136"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_responses", sa.Column("checklist_id", sa.String(length=40), nullable=True)
    )
    conn = op.get_bind()
    conn.execute(
        sa.text("""
        UPDATE user_responses ur
        JOIN controls c ON ur.control_id = c.id
        SET ur.checklist_id = c.checklist_id
        WHERE ur.checklist_id IS NULL or ur.checklist_id = ''
    """)
    )
    op.alter_column(
        "user_responses",
        "checklist_id",
        existing_type=sa.String(length=40),
        nullable=False,
    )
    op.create_index(
        "ix_user_responses_checklist_id",
        "user_responses",
        ["checklist_id"],
        unique=False,
    )

    op.create_foreign_key(
        "fk_user_responses_checklist",  # explicit name
        "user_responses",
        "checklists",
        ["checklist_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_responses", type_="foreignkey")
    op.drop_index("ix_user_responses_checklist_id", table_name="user_responses")
    op.drop_column("user_responses", "checklist_id")
    # ### end Alembic commands ###
