"""status fields in app and chk

Revision ID: 875e718b470a
Revises: 452f868c8f72
Create Date: 2025-10-06 11:19:05.201199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '875e718b470a'
down_revision: Union[str, Sequence[str], None] = '452f868c8f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('status', sa.String(length=40), nullable=False))
    op.add_column('checklists', sa.Column('status', sa.String(length=40), nullable=False))
    op.add_column('checklists', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'comment')
    op.drop_column('checklists', 'status')
    op.drop_column('applications', 'status')
    # ### end Alembic commands ###
