"""added priority and department fix

Revision ID: 921417d3f292
Revises: de35b1cd7a42
Create Date: 2025-09-12 12:41:48.424421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '921417d3f292'
down_revision: Union[str, Sequence[str], None] = 'de35b1cd7a42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('priority', sa.Integer(), nullable=False))
    op.add_column('applications', sa.Column('department', sa.String(length=128), nullable=True))
    op.add_column('checklists', sa.Column('priority', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checklists', 'priority')
    op.drop_column('applications', 'department')
    op.drop_column('applications', 'priority')
    # ### end Alembic commands ###
