"""added description field to controls

Revision ID: a152e24a6f59
Revises: 921417d3f292
Create Date: 2025-09-15 10:47:41.340575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a152e24a6f59'
down_revision: Union[str, Sequence[str], None] = '921417d3f292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('controls', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('controls', 'description')
    # ### end Alembic commands ###
