"""added priority setting

Revision ID: ac55e523dc50
Revises: 875e718b470a
Create Date: 2025-10-07 12:37:25.500218

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "ac55e523dc50"
down_revision: Union[str, Sequence[str], None] = "875e718b470a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_priorities",
        sa.Column("user_id", sa.String(length=40), nullable=False),
        sa.Column("target_type", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.String(length=40), nullable=False),
        sa.Column(
            "priority", sa.Integer(), nullable=False, server_default=sa.text("2")
        ),
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_user_priority_unique",
        "user_priorities",
        ["user_id", "target_type", "target_id"],
        unique=True,
    )
    op.drop_column("applications", "priority")
    op.drop_column("checklists", "priority")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "checklists",
        sa.Column("priority", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "applications",
        sa.Column("priority", mysql.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_index("ix_user_priority_unique", table_name="user_priorities")
    op.drop_table("user_priorities")
    # ### end Alembic commands ###
