"""Add is_completed column to checklists

Revision ID: ad60839b30f0
Revises: 5577c549c070
Create Date: 2025-09-03 11:29:40.912777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ad60839b30f0'
down_revision: Union[str, Sequence[str], None] = '5577c549c070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_controls_checklist_id'), table_name='controls')
    op.drop_table('controls')
    op.drop_index(op.f('name'), table_name='applications')
    op.drop_table('applications')
    op.drop_table('checklist_assignments')
    op.drop_index(op.f('ix_user_responses_control_id'), table_name='user_responses')
    op.drop_index(op.f('ix_user_responses_user_id'), table_name='user_responses')
    op.drop_table('user_responses')
    op.drop_table('checklists')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=15), nullable=False),
    sa.Column('mfa_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('mfa_secret', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('mfa_recovery_codes', mysql.JSON(), nullable=True),
    sa.Column('last_login', mysql.DATETIME(), nullable=True),
    sa.Column('disabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('checklists',
    sa.Column('app_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('checklist_type', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('creator_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['applications.id'], name='checklists_ibfk_1'),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='checklists_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_responses',
    sa.Column('control_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('current_setting', mysql.TEXT(), nullable=True),
    sa.Column('review_comment', mysql.TEXT(), nullable=True),
    sa.Column('evidence_path', mysql.TEXT(), nullable=True),
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['control_id'], ['controls.id'], name=op.f('user_responses_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_responses_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_responses_user_id'), 'user_responses', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_responses_control_id'), 'user_responses', ['control_id'], unique=False)
    op.create_table('checklist_assignments',
    sa.Column('checklist_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('checklist_assignments_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('checklist_assignments_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('applications',
    sa.Column('name', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('platform', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('region', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('creator_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('owner_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('provider_name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('infra_host', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('app_tech', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], name='applications_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('name'), 'applications', ['name'], unique=True)
    op.create_table('controls',
    sa.Column('checklist_id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('control_area', mysql.VARCHAR(length=36), nullable=False),
    sa.Column('severity', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('control_text', mysql.TEXT(), nullable=False),
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['checklist_id'], ['checklists.id'], name=op.f('controls_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_controls_checklist_id'), 'controls', ['checklist_id'], unique=False)
    # ### end Alembic commands ###
