"""increased text sizes

Revision ID: d8a91ba62e8c
Revises: a3488891ab8e
Create Date: 2025-09-09 15:15:30.389577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd8a91ba62e8c'
down_revision: Union[str, Sequence[str], None] = 'a3488891ab8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('applications', 'name',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('applications', 'platform',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('applications', 'region',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('applications', 'owner_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('applications', 'provider_name',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=666),
               existing_nullable=False)
    op.alter_column('applications', 'infra_host',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('checklists', 'checklist_type',
               existing_type=mysql.VARCHAR(length=25),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('controls', 'control_area',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('controls', 'severity',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('controls', 'control_text',
               existing_type=mysql.LONGTEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=False)
    op.alter_column('user_responses', 'current_setting',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('user_responses', 'review_comment',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    op.alter_column('user_responses', 'evidence_path',
               existing_type=mysql.TEXT(),
               type_=mysql.MEDIUMTEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_responses', 'evidence_path',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('user_responses', 'review_comment',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('user_responses', 'current_setting',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('controls', 'control_text',
               existing_type=mysql.MEDIUMTEXT(),
               type_=mysql.LONGTEXT(),
               existing_nullable=False)
    op.alter_column('controls', 'severity',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=10),
               existing_nullable=False)
    op.alter_column('controls', 'control_area',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('checklists', 'checklist_type',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=25),
               existing_nullable=False)
    op.alter_column('applications', 'infra_host',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)
    op.alter_column('applications', 'provider_name',
               existing_type=sa.String(length=666),
               type_=mysql.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('applications', 'owner_name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)
    op.alter_column('applications', 'region',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('applications', 'platform',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('applications', 'name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###
