"""added priority and department

Revision ID: de35b1cd7a42
Revises: 1cb81c2ab647
Create Date: 2025-09-12 11:55:12.741411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "de35b1cd7a42"
down_revision: Union[str, Sequence[str], None] = "1cb81c2ab647"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "applications",
        sa.Column("priority", sa.Integer(), server_default="2", nullable=False),
    )
    op.add_column(
        "applications", sa.Column("department", sa.String(length=128), nullable=True)
    )
    op.add_column(
        "checklists",
        sa.Column("priority", sa.Integer(), server_default="2", nullable=False),
    )
    op.execute("UPDATE applications SET priority = 2 WHERE priority = 0 ;")
    op.execute("UPDATE checklists SET priority = 2 WHERE priority = 0 ;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("checklists", "priority")
    op.drop_column("applications", "department")
    op.drop_column("applications", "priority")
    # ### end Alembic commands ###
