"""addedd pre-assessment

Revision ID: e1a2cbf9cbe4
Revises: 7ba26179c1fd
Create Date: 2025-09-17 15:53:02.991509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "e1a2cbf9cbe4"
down_revision: Union[str, Sequence[str], None] = "7ba26179c1fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def downgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("answers")
    op.drop_table("pre_assessments")
    op.drop_table("sections")
    op.drop_table("questions")
    op.drop_table("submissions")
    op.create_foreign_key(
        None, "user_responses", "checklists", ["checklist_id"], ["id"]
    )
    # ### end Alembic commands ###


def upgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_user_responses_checklist", "user_responses", type_="foreignkey"
    )
    op.create_table(
        "submissions",
        sa.Column("user_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("assessment_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("status", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["pre_assessments.id"], name="submissions_ibfk_2"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name="submissions_ibfk_1"),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "questions",
        sa.Column("section_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("question_text", mysql.TEXT(), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["section_id"], ["sections.id"], name="questions_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "sections",
        sa.Column("assessment_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("title", mysql.VARCHAR(length=512), nullable=False),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"], ["pre_assessments.id"], name="sections_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "pre_assessments",
        sa.Column("assessment_type", mysql.VARCHAR(length=512), nullable=False),
        sa.Column("description", mysql.TEXT(), nullable=True),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    op.create_table(
        "answers",
        sa.Column("submission_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("question_id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("answer_text", mysql.TEXT(), nullable=True),
        sa.Column("id", mysql.VARCHAR(length=40), nullable=False),
        sa.Column("created_at", mysql.DATETIME(), nullable=False),
        sa.Column("updated_at", mysql.DATETIME(), nullable=False),
        sa.Column(
            "is_active",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"], ["questions.id"], name=op.f("answers_ibfk_2")
        ),
        sa.ForeignKeyConstraint(
            ["submission_id"], ["submissions.id"], name=op.f("answers_ibfk_1")
        ),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb4_0900_ai_ci",
        mysql_default_charset="utf8mb4",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
